// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../source/ui/button.js', ['tv.ui.Button'], ['tv.ui', 'tv.ui.Component']);
goog.addDependency('../../../source/ui/component.js', ['tv.ui.Component'], ['goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.style', 'tv.ui', 'tv.ui.Document']);
goog.addDependency('../../../source/ui/container.js', ['tv.ui.Container'], ['goog.dom', 'goog.dom.classes', 'goog.math.Coordinate', 'goog.style', 'goog.userAgent.product', 'tv.ui', 'tv.ui.Component']);
goog.addDependency('../../../source/ui/decorate_handler.js', ['tv.ui.DecorateHandler'], ['goog.array']);
goog.addDependency('../../../source/ui/document.js', ['tv.ui.Document'], ['goog.events.EventHandler', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.events.KeyHandler']);
goog.addDependency('../../../source/ui/grid.js', ['tv.ui.Grid'], ['tv.ui.Container']);
goog.addDependency('../../../source/ui/input.js', ['tv.ui.Input'], ['goog.dom', 'goog.dom.selection', 'goog.events.InputHandler', 'tv.ui', 'tv.ui.Component']);
goog.addDependency('../../../source/ui/lightbox.js', ['tv.ui.Lightbox'], ['tv.ui.Container']);
goog.addDependency('../../../source/ui/link.js', ['tv.ui.Link'], ['tv.ui', 'tv.ui.Button']);
goog.addDependency('../../../source/ui/menu.js', ['tv.ui.Menu'], ['goog.functions', 'tv.ui.Container']);
goog.addDependency('../../../source/ui/sub_menu.js', ['tv.ui.SubMenu'], ['goog.functions', 'tv.ui.Container']);
goog.addDependency('../../../source/ui/tab_container.js', ['tv.ui.TabContainer'], ['tv.ui.Container']);
goog.addDependency('../../../source/ui/toggle_button.js', ['tv.ui.ToggleButton'], ['tv.ui', 'tv.ui.Button']);
goog.addDependency('../../../source/ui/ui.js', ['tv.ui'], ['goog.array', 'goog.dom']);
