// This file was autogenerated.
// Please do not edit.
goog.addDependency('../../../ui/button.js', ['tv.ui.Button'], ['tv.ui', 'tv.ui.Component']);
goog.addDependency('../../../ui/component.js', ['tv.ui.Component'], ['goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.style', 'tv.ui', 'tv.ui.Document']);
goog.addDependency('../../../ui/container.js', ['tv.ui.Container'], ['goog.dom', 'goog.dom.classes', 'goog.math.Coordinate', 'goog.style', 'tv.ui', 'tv.ui.Component']);
goog.addDependency('../../../ui/decorate_handler.js', ['tv.ui.DecorateHandler'], ['goog.array']);
goog.addDependency('../../../ui/deps.js', [], []);
goog.addDependency('../../../ui/document.js', ['tv.ui.Document'], ['goog.events.EventHandler', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.events.KeyHandler']);
goog.addDependency('../../../ui/grid.js', ['tv.ui.Grid'], ['tv.ui.Container']);
goog.addDependency('../../../ui/input.js', ['tv.ui.Input'], ['goog.dom', 'goog.dom.selection', 'goog.events.InputHandler', 'tv.ui', 'tv.ui.Component']);
goog.addDependency('../../../ui/lightbox.js', ['tv.ui.Lightbox'], ['tv.ui.Container']);
goog.addDependency('../../../ui/link.js', ['tv.ui.Link'], ['tv.ui', 'tv.ui.Button']);
goog.addDependency('../../../ui/menu.js', ['tv.ui.Menu'], ['tv.ui.Button', 'tv.ui.TabContainer']);
goog.addDependency('../../../ui/tab_container.js', ['tv.ui.TabContainer'], ['tv.ui.Container']);
goog.addDependency('../../../ui/toggle_button.js', ['tv.ui.ToggleButton'], ['tv.ui', 'tv.ui.Button']);
goog.addDependency('../../../ui/ui.js', ['tv.ui'], ['goog.array', 'goog.dom']);
